---
title: "Untitled"
author: "Derek (PID: A16942232)"
format: html
editor: visual
---
# Can you improve this analysis code?

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
library(bio3d)
protein.process <- function(x) {
  new.pdb <- read.pdb(pdb, "calpha")
  chainA <- trim.pdb(x)
}

protein.process("4AKE")
```

```{r}
read.pdb("4AKE")
```


Make this into a function

-1st get a simple working snippet
-make it as simple as possible
-reduce code duplication
-then turn into a function
-test it and fix errors
Points if it works, if it has comments, if we reduce duplication. 
